version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: check
          command: npm run check

      - run:
          name: coveralls
          command: npm run coveralls
